// this file auto-generated by the e_cpu assembler -- edits will be overwritten

#ifndef _GEN_other_H_
#define _GEN_other_H_

// from assembler DEF directives:

//#define USE_OTHER    // DEFh 0x0
#define VAL_USE_OTHER 0

#endif
