// auto-generated file -- do not edit by hand
void extint_init() {
	extern void ALE_2G_main();
ALE_2G_main();
	extern void CW_decoder_main();
CW_decoder_main();
	extern void CW_skimmer_main();
CW_skimmer_main();
	extern void DRM_main();
DRM_main();
	extern void FAX_main();
FAX_main();
	extern void FFT_main();
FFT_main();
	extern void FSK_main();
FSK_main();
	extern void FT8_main();
FT8_main();
	extern void IBP_scan_main();
IBP_scan_main();
	extern void IQ_display_main();
IQ_display_main();
	extern void Loran_C_main();
Loran_C_main();
	extern void NAVTEX_main();
NAVTEX_main();
	extern void SSTV_main();
SSTV_main();
	extern void S_meter_main();
S_meter_main();
	extern void ant_switch_main();
ant_switch_main();
	extern void colormap_main();
colormap_main();
	extern void devl_main();
devl_main();
	extern void digi_modes_main();
digi_modes_main();
	extern void iframe_main();
iframe_main();
	extern void noise_blank_main();
noise_blank_main();
	extern void noise_filter_main();
noise_filter_main();
	extern void s4285_main();
s4285_main();
	extern void timecode_main();
timecode_main();
	extern void waterfall_main();
waterfall_main();
	extern void wspr_main();
wspr_main();
}